### PR TITLE
Update Contribution.md

### PR DESCRIPTION
**Pull request by zahinekbal**
I Updated Contribution.md..
kindly check it ...

### CODE REVIEW

**Comment by Yash1256** [comment]
@zahinekbal I am Impressed with your work in frontend So can u update our Contributors and README to look more enhanced, clear and expressive. Would you like to work on it?

**Comment by zahinekbal** [comment]
Thankyou so much
Yeah I will try to do ...
But please what I have to do ? Mns in readme?

**Comment by Yash1256** [comment]
I am just sharing u a reference of expressive [README file](https://github.com/siddharth25pandey/CPP-Programming/blob/master/README.md). I don't want to make exactly README but enhanced version of this, So do you think it should be implemented or not. Just Comment out your views.

**Comment by Yash1256** [comment]
@zahinekbal Any Updates Regarding above Question?

**Comment by zahinekbal** [comment]
Yeah we can update readme file..

**Comment by Yash1256** [comment]
So would you like to work on this??

**Pull request merged**
