### PR TITLE
Add Cats and a Mouse Hackerrank solution

### PR DESCRIPTION
**Pull request by niranjantuty**
Added Cats and a Mouse Hackerrank solution in Python.

### CODE REVIEW

**Comment by niranjantuty** [comment]
If anything is wrong please inform me.  To make this PR a valid for Hacktoberfest, Please add 'hacktoberfest' topic to this repository or add 'hacktoberfest-accepted' label to this PR.

**Comment by niranjantuty** [comment]
@Yash1256  As I said can you please add "hacktoberfest" topic to this repo or add the 'hacktoberfest-accepted' label to this PR. Refer: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by Yash1256** [comment]
@niranjantuty Kindly Check the Repo Before contributing. It's Already There HacktoberFest Written and If you are just participating in this for the shirt so I am not prefering take contributions for that.. So you can try on other REPO.

**Comment by niranjantuty** [comment]
@Yash1256 I have completed my hacktoberfest challenge and this is my 7th PR this month.  I didn't make this PR just for a t-shirt.  I thought it might help others if you include those changes in your repo.  Anyway, Thank you for your 'hacktoberfest didn't accepted' label.

**Comment by Yash1256** [comment]
> As I said can you please add "hacktoberfest" topic to this repo or add the 'hacktoberfest-accepted' label to this PR. Refer: https://hacktoberfest.digitalocean.com/hacktoberfest-update

Then Why Have you said about this?

**Comment by niranjantuty** [comment]
@Yash1256 I thought it might help others to complete their hacktoberfest challenge.  But it is up to you.

**Pull request merged**
