### PR TITLE
Solution of C question

### PR DESCRIPTION
**Pull request by karunakeshari**

### CODE REVIEW

**Comment by Yash1256** [comment]
@karunakeshari First of all (*.exe) file are not needed, also add the Question in README.md of Hackerank Folder, and no need to make an extra folder inside Hackerrank.
Second thing I didn't get the first 2 files which are in xml language, Can u explain me the Use of those files (`Hackerrank/FunctionsInC.c/Functions in C.c.cbp` and `Hackerrank/FunctionsInC.c/Functions in C.c.layout`) that why have u pushed those two files?

**Comment by karunakeshari** [comment]
I will add question in Readme file and will make improvements on other
things
Thankyou for your feedback
It is my first pull request

**Comment by Yash1256** [comment]
>It is my first pull request

Good Going @karunakeshari

**Comment by Yash1256** [comment]
@karunakeshari are you working on your PR ?

**Comment by karunakeshari** [comment]
Yes I am working I will complete it soon

**Pull request closed without merging**
